//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.15 at 10:58:15 AM EST 
//

package com.safe.hsap.domainobjects.services;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="officePickCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="officeReturnCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idReservation" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "startDate", "endDate", "officePickCode", "officeReturnCode", "idReservation" })
@XmlRootElement(name = "updateReservation")
public class UpdateReservation {

	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date startDate;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date endDate;
	@XmlElement(required = true)
	protected String officePickCode;
	@XmlElement(required = true)
	protected String officeReturnCode;
	protected long idReservation;

	/**
	 * Gets the value of the startDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * Sets the value of the startDate property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setStartDate(Date value) {
		this.startDate = value;
	}

	/**
	 * Gets the value of the endDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * Sets the value of the endDate property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setEndDate(Date value) {
		this.endDate = value;
	}

	/**
	 * Gets the value of the officePickCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOfficePickCode() {
		return officePickCode;
	}

	/**
	 * Sets the value of the officePickCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOfficePickCode(String value) {
		this.officePickCode = value;
	}

	/**
	 * Gets the value of the officeReturnCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOfficeReturnCode() {
		return officeReturnCode;
	}

	/**
	 * Sets the value of the officeReturnCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setOfficeReturnCode(String value) {
		this.officeReturnCode = value;
	}

	/**
	 * Gets the value of the idReservation property.
	 * 
	 */
	public long getIdReservation() {
		return idReservation;
	}

	/**
	 * Sets the value of the idReservation property.
	 * 
	 */
	public void setIdReservation(long value) {
		this.idReservation = value;
	}

}
